#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Notifications
dunst &

# Switch between english and spanish keyboard
setxkbmap -option grp:alt_shift_toggle us,es &

# picom --experimental-backend &

bspc monitor -d I II III IV
xrandr --output HDMI-0 --mode 3440x1440

# Set the border colors.
bspc config normal_border_color \#000000
bspc config active_border_color \#ABE9B3
bspc config focused_border_color \#ABE9B3
bspc config presel_feedback_color \#161320 

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
bspc config top_padding 0

bspc config focus_follows_pointer false

bspc rule -a discord desktop='^4' follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Peek floating=true center=true

# Remove the x cursor
xsetroot -cursor_name left_ptr &

#Polybar Launching
~/.config/programs/polybar/./launch.sh

#enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1

feh --bg-fill ~/.config/wallpapers/pixelart_night_train_cozy_gas_warm-color.png &
